language: python
python:
- '2.7'

before_deploy:
- make

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: plugin.video.lostfilm.tv-${TRAVIS_TAG:1}.zip
  skip_cleanup: true
  overwrite: true
  on:
    repo: Nemiroff/plugin.video.lostfilm.tv
    tags: true
